### PR TITLE
chore: merge latest from upstream repo

### PR DESCRIPTION
**Pull request by eaddingtonwhite**
Main driver of this is so we can publish new momento-proxy container with latest version of Rust sdk so works w/ newer token format. Also @brayniac has added support for Dictionaries, Sets, Lists as well.

### CODE REVIEW

**Comment by danielamiao** [comment]
@eaddingtonwhite nothing internally we have depends on this repo right now, right? This won't break anything?

**Comment by eaddingtonwhite** [comment]
@danielamiao Nope this is just for end customers consuming our docker image of proxy once I publish new version after merging this. I don't think there are any breaking changes in this either.

**Review by cprice404 — APPROVED** [review]
@eaddingtonwhite i'm good with this but just make sure you don't accidentally do a squash merge!

**Comment by eaddingtonwhite** [comment]
@cprice404 good call out! Yes purposefully did not make that default merge option on this repo 😅

**Pull request merged**
